/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutStudioSection: typeof import('./components/AboutStudioSection.vue')['default']
    CaseDetailPage: typeof import('./components/cases/CaseDetailPage.vue')['default']
    CasesHeroBackground: typeof import('./components/cases/CasesHeroBackground.vue')['default']
    ContactMap: typeof import('./components/contact/ContactMap.vue')['default']
    ContactsSection: typeof import('./components/landing/ContactsSection.vue')['default']
    ContactWhatsAppPicker: typeof import('./components/contact/ContactWhatsAppPicker.vue')['default']
    HomeCanvasBackdrop: typeof import('./components/landing/HomeCanvasBackdrop.vue')['default']
    HomeCtaSection: typeof import('./components/landing/HomeCtaSection.vue')['default']
    HomeHeroSection: typeof import('./components/landing/HomeHeroSection.vue')['default']
    HomeMarquee: typeof import('./components/landing/HomeMarquee.vue')['default']
    HomePricingSection: typeof import('./components/landing/HomePricingSection.vue')['default']
    HomeProcessSection: typeof import('./components/landing/HomeProcessSection.vue')['default']
    HomeServicesSection: typeof import('./components/landing/HomeServicesSection.vue')['default']
    ProjectDiscussDialog: typeof import('./components/landing/ProjectDiscussDialog.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteFooter: typeof import('./components/landing/SiteFooter.vue')['default']
    SiteHeader: typeof import('./components/landing/SiteHeader.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
