/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CaseDetailPage: typeof import('./components/cases/CaseDetailPage.vue')['default']
    ContactsSection: typeof import('./components/landing/ContactsSection.vue')['default']
    ProjectDiscussDialog: typeof import('./components/landing/ProjectDiscussDialog.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteFooter: typeof import('./components/landing/SiteFooter.vue')['default']
    SiteHeader: typeof import('./components/landing/SiteHeader.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
